remote_theme: yaoyao-liu/minimal-light
# Basic Information 
title: Xiangyu Sun
position: Undergraduate Student
affiliation: University of Electronic Science and Technology of China (UESTC)
affiliation_link: https://www.uestc.edu.cn/
email1: sunx4382@gmail.com
email2: 2022040908003@std.uestc.edu.cn

# Search Engine Optimization (SEO)
keywords: Xiangyu Sun, UESTC, Robotics, Computer Vision, Vision-Language Models, Generalization
description: Personal homepage of Xiangyu Sun, a third-year undergraduate student at UESTC with interests in Robotics and Computer Vision.
canonical: https://mu9enn.github.io/

# Links 
google_scholar: https://scholar.google.com.hk/citations?user=tXofRmcAAAAJ&hl=zh-CN
github_link: https://github.com/mu9enn
cv_link: assets/files/Resume_of_XiangyuSun.pdf
# linkedin: https://www.linkedin.com/in/your-profile
# twitter: https://x.com/awku585287

# Images 
# avatar: ./assets/img/selfie.jpg  # Upload your profile picture here
avatar: ./assets/img/gray_image.jpg
favicon: ./assets/img/icon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Google Analytics ID (optional)
# google_analytics: UA-XXXXX-X  # Remove if not using
